import './globals.css';
import type { Metadata } from 'next';

import { Suspense } from 'react';

import Header from './Header';
import Footer from './Footer';
import Loading from './_loading';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='ja'>
      <body className='container mx-auto bg-slate-700 text-slate-50'>
        <div className='flex flex-col min-h-screen'>
          <Header />
          <Suspense fallback={<Loading />}>
            <main className='flex-grow'>{children}</main>
          </Suspense>
          <Footer />
        </div>
      </body>
    </html>
  );
}
